name: I have this condition
favicon: null
layout_spectrum: 0.4466978085692972
typography_spectrum: 0.5303427102044225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9263668693602085
  lightness: 0.5439470722340047
  saturation: 0.7709914871957153
  rhythmicContrast: 0.28445897763594985
purpose: []
